### ISSUE TITLE
UI Redesign to improve existing and add new features

### ISSUE THREAD

**Issue by grote** [seedvault-app/seedvault#117]
Seedvault's UI either needs to be redesigned or the current design adapted to accommodate additional functionality we want to add to the app.

I give a feature list below to have an overview over new and existing functionality:

* Initial Setup
  * **[NEW]** Setup in devices setup-wizard on first boot #63
  * **[NEW]** Initial onboarding explaining subsequent step #86
  * recovery code writing down and re-entering for confirmation
  * backup storage selection
* Status information
   * time of last backup
   * current backup location
   * app status information
       * app backup status (ok, not allowed, no data, error, etc.)
       * time of last app backup
       * app included/excluded from backup
    * **[NEW]** size of backup? (unclear if should be shown)
    * **[NEW]** time of last SMS (texts) backup (unclear if should be shown)
    * **[NEW]** time of last call log backup (unclear if should be shown) #93
    * **[NEW]** time of last local contacts backup (unclear if should be shown) #66
    * **[NEW]** time of last settings backup (unclear if should be shown)
    * **[NEW]** time (and size?) of last external data storage backup (unclear if should be shown, per folder?) #36 #57
* Settings
  * backup on/off
  * change backup location
  * enable/disable automatic restore
  * backup off app APKs on/off
  * exclude individual apps from backup
  * **[NEW]** add/remove external folder to get backed up (e.g. Photos, Music, Signal Backup)  #36 #57
* **[NEW]** Restore Set management #100
  * **[NEW]** list all backups in the storage location (and their time and size?)
  * **[NEW]** start using a new/fresh backup for subsequent backup (leaves current/old ones available for later)
  * **[NEW]** delete old backups
* **[NEW]** verify recovery code (to ensure we have the right one)
* **[NEW]** change recovery code if lost (will delete all old backups, if possible) #62
* Make/trigger backup now
* About screen

Currently, status and settings are somewhat mixed and there has been feedback that users weren't sure if backup is working. However, this also related to the inability to do (full) restores without factory reset.

**Comment by chirayudesai** [comment]
> Seedvault's UI either needs to be redesigned or the current design adapted to accommodate additional functionality we want to add to the app.
> 
> I give a feature list below to have an overview over new and existing functionality:
> 
> * Initial Setup
>   
>   * **[NEW]** Setup in devices setup-wizard  #63
"Setup from SetupWizard on first boot"
Also need to consider how nextcloud will work for this. Might get complicated, perhaps one thing we can for now is simply show a notification on first boot "Tap to setup backup" (after SUW) that just takes you to Seedvault.
>   * **[NEW]** Initial onboarding explaining subsequent step #86
"Introduction screen, before we show the recovery code"
This should be the first step.
>   * recovery code writing down and re-entering for confirmation
**[TODO]** See if we can integrate with the keyboard better.
>   * backup storage selection
> * Status information
>   
>   * time of last backup
>   * current backup location
>   * app status information
>     
>     * app backup status (ok, not allowed, no data, error, etc.)
>     * time of last app backup
>     * app included/excluded from backup
>   * **[NEW]** size of backup? (unclear if should be shown)
Size of overall backup would be good to have.
>   * **[NEW]** time of last SMS (texts) backup (unclear if should be shown)
Should be shown!
>   * **[NEW]** time of last call log backup (unclear if should be shown) #93
Should be shown!
>   * **[NEW]** time of last local contacts backup (unclear if should be shown) #66
Should be shown!
>   * **[NEW]** time of last settings backup (unclear if should be shown)
Should be shown!
All of these are basically just mapping a package to a user-friendly name. :)
>   * **[NEW]** time (and size?) of last external data storage backup (unclear if should be shown, per folder?) #36 #57
> * Settings
This will depend on how we end up implementing this, should be shown if we can though. Let's assume we'll show it for now to have accommodation for it in the design.
>   
>   * backup on/off
>   * change backup location
>   * enable/disable automatic restore
This could maybe we worded better.
>   * backup off app APKs on/off
Same here perhaps.
>   * exclude individual apps from backup
>   * **[NEW]** add/remove external folder to get backed up (e.g. Photos, Music, Signal Backup)  #36 #57
> * **[NEW]** Restore Set management #100
Should definitely find a good user-facing name for this.
>   
>   * **[NEW]** list all backups in the storage location (and their time and size?)
Time / device - same menu as what you get during restore would be good to have.
Size could be a nice plus.
>   * **[NEW]** make a new backup (leaved current/old ones available for later)
Covered by restore sets?
>   * **[NEW]** delete old backups
> * **[NEW]** verify recovery code (to ensure we have the right one)
Much needed!
> * **[NEW]** change recovery code if lost (will delete all old backups, requires storage present) #62
Should not require storage for this, for more see linked issue.
> * Make/trigger backup now
Maybe move this out of the menu?
> * About screen
> 
> Currently, status and settings are somewhat mixed and there has been feedback that users weren't sure if backup is working. However, this also related to the inability to do (full) restores without factory reset.

Yes, I would like for there to be a separate main screen that just shows the status, and then you can go the Settings to get a screen like the one we currently have.

I think that's a better UI paradigm to follow rather than dumping the user directly into settings.

**Comment by grote** [comment]
From a development schedule perspective, designs for these features is most urgent:

System backup info:

* show time of last SMS (texts) backup (unclear if should be shown)
* show time of last call log backup (unclear if should be shown) #93
* show time of last local contacts backup (unclear if should be shown) #66
* show time of last settings backup (unclear if should be shown)

Recovery code:

* verify recovery code (to ensure we have the right one)
* change recovery code if lost (will delete all old backups, if possible)

**Comment by glenn-sorrentino** [comment]
I've also taken the opportunity to address some other usability issues on the main settings page and the drill-in.

Here's a quick animation of the two screens:
[SeedVault App Data Backup Settings ](https://keybase.pub/glennsorrentino/CalyxOS/Demo/seedvault-status-drill-in.gif)

Most of the issues I'm seeing are with IA, UI text, and accessibility.

**Backup Settings Home**
1. The parent setting "Backup my data" and "App backup" are confusingly similar. Even with the secondary text, I think this'll cause issues with users.
2. The section labeled "App data backup" is too limiting. Settings include options that fall outside of the app's data.

**App Backup Status**
1. At first glance, I see a lot of warning icons. It looks like a lot is going wrong.
2. There's a lot of redundant UI text from the apps that do not allow backups.
3. The green checkmark is too dark to give sufficient color contrast for the dark background.

Solutions center around improved information hierarchy with a better grouping of similar kinds of information and functionality and clearer UI text.

**Backup Settings Home**
1. Group backup-level toggles together.
2. Group more granular settings together.

**App Data Backup Settings**
1. Group apps by type -system, user-installed, ineligible apps
2. Is there an opportunity to provide relevant information?
3. Make all status iconography in dark mode white.

![usability-issues(1)](https://user-images.githubusercontent.com/28545431/94503027-57972480-01ba-11eb-8b95-606b83ed71d4.png)
![high-level-solutions(1)](https://user-images.githubusercontent.com/28545431/94503380-2d923200-01bb-11eb-800d-d7d65f73d573.png)

**Comment by grote** [comment]
Google's backup status:

The `Waiting to back up...` text and the system app icons are interesting.

![Screenshot_20200816-025614](https://user-images.githubusercontent.com/244947/94680502-350b2580-02f8-11eb-844f-24f504d71ef9.png)

**Comment by grote** [comment]
Thanks a lot @glenn-sorrentino, this looks great and is definitely an improvement on the current design! 

There's a few questions or uncertainties I have:

> Group backup-level toggles together.

This makes sense, but I am not sure the copy for the second toggle is clear enough:

    App backup

    Back up only the apps on your phone

If I would read this, I would think if this is off, no app would get backed up. But this is not what this toggle does. It controls backup of the APKs which is the app itself without data. Now the problem is that if this is off and we don't have an APK to re-install, we also can't restore data for the app (as it isn't even installed).

I wonder if we even need to expose this toggle (so prominently) as most users would want this on. It increases the storage requirement for backup considerably, but makes everything work. If it is off, you need to be an advanced technical user to figure out how to still restore your data.

For reference, this is how the copy of this setting is presented at the moment:

    App Backup

    Back up the apps themselves. Otherwise, only app data would get backed up.

> Group more granular settings together.

Oh wait. I now realize that in the video there's `App Backup` and `App Data Backup`. What is the `App Backup` toggle supposed to do?

> App Data Backup Settings

This is currently called `App data backup status` probably because it shows you the backup status of your apps. However, now it also shows system backup status, so the name could be simplified and generalized to just `Backup status`?

> Group apps by type -system, user-installed, ineligible apps

What should we do with apps that we can't backup for other reasons?

* Technically, ineligible apps are not only those that explicitly opt-out of getting backed up, but also those that were [force stopped](https://github.com/stevesoltys/seedvault/wiki/FAQ#why-do-apps-not-get-backed-up-when-not-recently-used) for some reason. 
* After setting up backup (but also later) many apps are in a "waiting to back up..." state.
* There's apps that exceed the backup quota.
* Apps can also not report any data to get backed up (usually because they are so simple that they don't store data, or haven't had the chance to store data yet)
* Then there's apps that just fail and we don't know why.

Then within a group we just sort the apps alphabetically as we do now?

The system data backup group is not giving the time of the last backup, just saying "Backup up successfully". Is this intentional?

> Is there an opportunity to provide relevant information?

I notice that the time of the last backup is shown twice. First in the status highlight and on the main settings screen as a preference summary. That doesn't need to be a bad think, just pointing it out.

As for other relevant information, we might be able to show how much space a backup takes up, but don't always know how much space is available on the storage medium.

Depending on how the grouping shall work, it might be helpful to show how many apps could get backed up vs. those that couldn't, so the user immediately sees that some couldn't get backed up without needing to scroll down to the end.

> Make all status iconography in dark mode white.

If we were to do the grouping by all error types, we might not need the status iconography at all as this information is par of the group an app is in.

Otherwise, what's the reason for making them white in dark mode? Making the colors more accessible?

> Smaller app icons for better data density.
> Reduced space between app name and secondary line for better density.

Do you have the `dp` values here or should they just be made a "bit" smaller?

**Comment by grote** [comment]
@glenn-sorrentino this is how the app list will look for now (note the icons) until we resolve the questions above:


![device-2020-10-23-135659](https://user-images.githubusercontent.com/244947/97032379-1df6d680-1538-11eb-8e1b-448f97d7d2a1.png)

**Comment by dznsm** [comment]
I'm thinking its worth considering showing more info about the size of the backup.  The 'pie-chart' of storage space used in the mock up of @glenn-sorrentino is nice. Maybe it should illustrate storage size, backup size & free space.

The other thing I was wondering about was showing the size of the backup for each app (data, apk & total) and sorting apps by backup size. For users with storage/bandwidth limits this data could be very useful. 

If this data could be calculated and displayed (expected sizes of next backup) at any time, or after backup failure, it shows the user whats using all the space and provides them with useful data for quickly/effectively significantly reducing backup sizes. eg. a podcast app can have large amounts of data, which due to data being readily availability via the web, users may be happy to skip for backup

**Comment by jtagcat** [comment]
> recovery code writing down and re-entering for confirmation

Don't ask for all words; though enable the user to optionally enter all words (to make them feel safe of no 'typos' (hard to do with the current system, but still) etc) (like ssh host key prompt of yes/no/paste the whole thing here)

with mnemonic, don't ask for the first and last 2 (as they are more likely to have been remembered by the user), pick a random from the middle (or even a set one, say 6th; this allows (dev) test use to not write stuff down)

**Comment by e-zk** [comment]
Perhaps a decent way to show apps that do/don't allow backups (without it looking like something has gone wrong) would be to do what the Android settings does for Installed+Disabled apps:

![Android app list from settings, showing drop-down](https://user-images.githubusercontent.com/58356365/111891326-e4ba8800-8a3d-11eb-970a-808500b7b75c.png)

Maybe have a similar drop-down that shows "Backing Up", and "Not Backed Up"?

**Comment by jtagcat** [comment]
It's too hidden, out of the way. If the user doesn't think to click on 'All apps', they will never know.

(and I still stand behind what I said — if 80% of apps are not being backed up, rightfully so, there should be obvious warning lights)

**Comment by rigrig** [comment]
About 50% of my apps have "App doesn't allow backup", but a few show "Backup quota exceeded". Those really don't stand out now, which I think is a problem: if you already went through the list, it is not obvious that another app suddenly is no longer backed up. (It doesn't help that they use the same icon)
Grouping by type of problem would solve this, maybe put error groups first to make them more obvious?

Maybe the top of the "App Backup Status" screen could (also) show a summary of backup status?
Something like (only show items where #N > 0)
:heavy_check_mark: #N apps backed up (this would be the total of system+user)
:hourglass: #N apps waiting to backup
:no_entry_sign: #N apps don't allow backups
:exclamation: #N apps failed to backup (this would be total of quota exceeded + other problems)
That way you can quickly check if the numbers changed, instead of having to go through the whole list.

Or maybe take it even further: make groups collapsible, start them all out collapsed and show the number of apps in the group header?

**Comment by grote** [comment]
I think we have implemented most of this. Let's open a new ticket for other things like #100.
