### ISSUE TITLE
Syncthing as a backup location

### ISSUE THREAD

**Issue by EmanuelLoos** [seedvault-app/seedvault#176]
If Seedvault could support a decentral file synchronization protocol like [Syncthing](https://en.wikipedia.org/wiki/Syncthing) ~~or [OnionShare](https://onionshare.org/)~~ it would be possible to automatically backup app data to a computer or if implemented really good even sync app data with a second phone without relying on any central server.

**Comment by grote** [comment]
Seedvault supports all storage providers that expose their storage to the android storage access framework. See #167 and #169 for example. AFAIK  OnionShare is not even available on Android and is for transferring single files only.

**Comment by stevesoltys** [comment]
As mentioned above, if Syncthing supports SAF, this may already work. If it doesn't, this would likely be a feature request for Syncthing.

Feel free to give it a shot and let us know!

**Comment by protomors** [comment]
As far as I know Syncthing does not support SAF. But I am already using it with Seedvault because Nextcloud is just too slow. I simply selected internal storage as backup location, added .SeedVaultAndroidBackup folder to Syncthing and shared it with my NAS. This way backups are stored on the phone but when I am on my home WiFi they are also uploaded to NAS. I am satisfied with results because Syncthing is very efficient with detecting and uploading only changed files.

**Comment by stevesoltys** [comment]
That sounds like a good solution to me @protomors.

Closing this for now. If additional information is needed, please continue this discussion in #180. Thanks!

**Comment by jtagcat** [comment]
Syncthing can pick up files in local storage. You can ignore the directory you'll be dumping the backup on local storage. Then on a remote device, move it outside the folder. (You can't just 'push' the file.)

**Comment by jt196** [comment]
@jtagcat I'm not totally sure what you're suggesting here. Why not just do a send only backup to your backup location? Is this to be able to save space on your phone/have multiple backups?

**Comment by jtagcat** [comment]
> Is this to be able to save space on your phone/have multiple backups?

Yes.

**Comment by anarcat** [comment]
> Syncthing can pick up files in local storage. You can ignore the directory you'll be dumping the backup on local storage. Then on a remote device, move it outside the folder. (You can't just 'push' the file.)

@jtagcat can you expand on how you actually did this? do you manually move files out of there? the seedvault storage format kind of look rather opaque to me ... how do you figure a backup is complete? do you have a cron job to pick up the backups automatically?

**Comment by jtagcat** [comment]
> > Syncthing can pick up files in local storage. You can ignore the directory you'll be dumping the backup on local storage. Then on a remote device, move it outside the folder. (You can't just 'push' the file.)
> 
> @jtagcat can you expand on how you actually did this? do you manually move files out of there? the seedvault storage format kind of look rather opaque to me ... how do you figure a backup is complete? do you have a cron job to pick up the backups automatically?

@anarcat:

At root of internal storage of the phone, there is a folder named `.SeedVaultAndroidBackup`. Syncthing sees it at `/storage/emulated/0/.SeedVaultAndroidBackup`. I sync that as Send Only.

> Do you have a cron job to pick up the backups automatically?

No. SeedVault manages it's backups itself. As a safety mechanism, you may use Syncthing's  file versioning, but I have disabled it, and rely on filesystem-level (ZFS) snapshots (and in addition, backups of the file system itself).

On the phone side, I have syncthing configured to not `Watch for Changes`, instead I only let it rescan once daily. Depending on your phone, and connectivity, it might be a good idea to let Syncthing only run only when charging and/or on WiFi. Syncthing-Fork enables you to do this on a per-share/folder basis (in case you use syncthing for anything else on your phone).

> Do you manually move files out of there?

So in the larger picture, it's a folder that's the same on both the device, and backup destination. After a backup is finished, I don't remove anything from the phone manually. It cleans up itself, and takes a few GiB, what is fine for me.

> The seedvault storage format kind of look rather opaque to me.

It's rather opaque to me as well. I just make sure SeedVault backups, and Syncthing syncs.

Testing backups is rather complicated as well, so I don't. Some apps break restoring, mostly ones with sign in and heavy cloud dependencies.

> How do you figure a backup is complete?

Normally, I don't. It is continually synced.

You have to monitor that SeedVault is actually backing up. While I have used it, it has sometimes stopped scheduled backups. I have also forgotten to resume backing up after a restore. An easy way to do this is to have a cronjob listing directories newer than n days (with `ls -Art`, or `exa -asnew`), and erroring if there isn't any output.

Second thing to monitor is Syncthing itself. (This didn't happen with the normal Syncthing app.) On some devices, Syncthing-Fork [halted after updating](https://github.com/Catfriend1/syncthing-android/issues/896). I noticed this by having devices offline.

Going advanced, you may set up something like Prometheus and Alertmanager for this, or consume the API.  
But instead, you can, every now and then, check either on the phone (or I prefer on destination device), that Syncthing has connected to the other device recently (`Last seen`), and that the syncing folder is `Up to date` (or if on phone, that the phone, that the destination device(s) don't have Out of Date items).

Besides watching connectivity of Syncthing, There isn't really a way to monitor from the server/backup destination, that Syncthing has scanned files recently, that I know of. But this is already covered by watching for new directories.

***

Besides SeedVault, I back up SMS via my SMS app, and [call logs via ADB](https://github.com/jtagcat/jtagcat/blob/main/scripts/adb/pull_calllog.sh), and a list of installed apps.

**Comment by anarcat** [comment]
oh, okay, super interesting thanks. so i guess the key thing here is that:

 1. you *do* keep the backups on device (I was hoping I could have seedvault "fire and forget" the backups: store them locally, and once syncthing has them, drop them to save disk space)
 2. you do it send-only (presumably to keep the remote machines from messing with the backups?)
 3. you monitor that syncthing runs

Thanks for the feedback, super useful!

**Comment by bickford** [comment]
Hi all, sorry to bump an old thread but I wanted to add that it is probably pointless to enable versioning in SyncThing for Seedvault backups directory / shared folder. I wanted to share my understanding of why, so that anyone with better info can correct me.

There's no way in SyncThing to do a 'point in time restore' for a root folder, so you'd be unable to restore the Seedvault backup folder back to a particular backup 'set'. So in a scenario where your latest backups were bad or overwrote important data for instance but you know your backups were good a week ago, I don't see how you'd do it. Not without a huge amount of effort checking dates on every file in .stversions (Syncthing's hidden version directory) and then you would still have to do some guesswork, as due to Android's backup architecture that Syncthing uses, not every app is backed up every backup run.

In a simpler second scenario where you are just trying to restore a single app backup that's been overwritten in Seedvault by a newer backup, you could possibly turn to an older version for that app stored in Syncthing's versions. However, unless I am mistaken it is hard to even know which app backup folder is a backup of which app, without first extracting all the apps via something like seedvault-extractor, and that project is no longer maintained though so you will likely run into further hurdles there.

So my takeaway is that trying to utilize Syncthing versioning for Seedvault backups is probably a waste of time and diskspace. Any thoughts?

**Comment by grote** [comment]
Yes, sounds like it. Seedvault keep recent snapshots and those should also contain things like older apps. The existence of certain snapshots may give you a clue for SyncThing, but only seedvault (check integrity) can tell you what is inside those snapshots.
