### ISSUE TITLE
Allow backing up multiple users profiles

### ISSUE THREAD

**Issue by Hugo22O** [seedvault-app/seedvault#208]
Hi all, 

Currently I am unable to backup multiple user profiles at once. I user over 3 user profiles with my custom ROM (GrapheneOS) because it has significant security benefits, but seedvault does not allow for backing up all of them. 

I'd be much appreciated if I could back-up all user profiles. For your information, I am by far not the only one that would like this feature from what I have seen on some Matrix channels. 

--

Also not sure if this has been requested before, I apologize if it has. Searching for user and user profiles didn't return any feature requests. 

Thank you.

**Comment by dznsm** [comment]
This can be enabled via adb. There's been some discussion about how to do so in [#77](https://github.com/stevesoltys/seedvault/issues/77#issuecomment-696752898). 
Theres an [issue](https://github.com/GrapheneOS/os_issue_tracker/issues/332) open on the GrapheneOS issue tracker.
I've [documented](https://hub.libranet.de/wiki/graphene-os/wiki/Backups#Backup_secondary_user_and_work_profiles) how to do backup and restore in secondary user profiles or work profiles.

**Comment by grote** [comment]
@dznsm great work! Would be nice if this could be copied also to the wiki here maybe?

**Comment by dznsm** [comment]
@grote I'd be happy to do that. By default there isn't public access to edit the wiki.
https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by dznsm** [comment]
@grote I've got a draft together, how would you like to progress. @stevesoltys

**Comment by grote** [comment]
Awesome, thanks!

The proposal is to open a PR with a markdown file for https://github.com/seedvault-app/seedvault.app which will later be integrated into a static website.

**Comment by crass** [comment]
@grote: There is a similar bug for GrapheneOS here GrapheneOS/os_issue_tracker#332. And the lead developer believes that turning on the backup manager service for a user should be the responsibility of Seedvault. Would that also be your understanding? I'm guessing not since this issue has been closed. Could you please comment on that GrapheneOS issue to help resolve this if so?

As I've commented in that issue, regardless of who's responsibility it should be, it would be great to have that turned on so that adb is not required in order to backup/restore non-Owner accounts. And this would be an intermediary step towards full support of multiple user profiles.

**Comment by grote** [comment]
pinging @chirayudesai for his opinion.

**Comment by crass** [comment]
@grote @chirayudesai  Checking back in. Any thoughts/conclusions on this?
