### ISSUE TITLE
Device backup filed to run

### ISSUE THREAD

**Issue by stelkintatko** [seedvault-app/seedvault#248]
Hi guys,
i was using nextcloud for backup. then, i switched to USB to make 1 backup there directly and wanted to revert back to nextcloud. however, now i get a notification drawer warning from Seedvault:

Backup error - Device backup failed to run.

if i hit the FIX link in the notification, it tries to contact nextcloud for ages - unsuccessfully and i get a message:

Initializing backup location....

An error occurred while accessing the backup location. <in red color>

BACK [button on the bottom].

What can i do to fix it please? Thank you!

**Comment by asuh** [comment]
Everything after switching to USB is identical to my issue with Seedvault and Nextcloud. I am on a Pixel 3a using CalyxOS with June 2021 updates.

@grote I have logcat logs and can add something here to help debug this issue, but I'm not sure what you're looking for. Let me know and I'll provide what I can.

**Comment by asuh** [comment]
I think I made good progress on my own.

I have Nextcloud running on a personal NAS. I had to go to the URL ending in`nextcloud/index.php/settings/admin/logging` in order to see what was happening there.

I keep seeing a repeating error:

```
[PHP] Error: Error: fread(): read of 8192 bytes failed with errno=21 Is a directory at [path_to_nextcloud_folder]/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#860
```

[This is a known issue with server-side encryption in Nextcloud](https://github.com/nextcloud/server/issues/21578).

I manually [applied a fix they added](https://github.com/nextcloud/server/pull/24966) but one that didn't seem to make it into the latest build.

After applying this patch, (either waiting or you can stop and restart the Nginx service) I stopped hearing the hard drives thrashing and the CPU processing went down. A few minutes later, I went back to the Backup section in CalyxOS and manually ran "Backup now" inside of the menu bullets on the top right. I'm finally seeing success!

Hope this helps someone else!
