### ISSUE TITLE
LineageOS: Can't restore from Nextcloud, because not available in SetupWizard

### ISSUE THREAD

**Issue by robbosch** [seedvault-app/seedvault#251]
I have set up SV to backup to Nextcloud. I run LineageOS 18.1 on a Xiaomi mi5. The backup is done fine (except for a few apps that don't allow for backup)
I do NOT use GAPPS or microg. I get my apps from f-droid.
After a factory reset, it is impossible to restore from nextcloud since the nexcloud client is not installed and there is no appstore to install it from. I need to initialize LOS first to be able to add f-droid and nextcloud client.
At this point, I can not initialize a restore from nextcloud.
Can this catch22 get a solution in some way?
(copying the SV directory from nextcloud to an SD card and pop in the SD card in the phone IMO is not a sustainable solution)

/edit: I managed to do a restore after first intializing Android.

- After factory reset of Android, finish first initialization of Android without restore
- install f-droid app
- from F-droid store install nextcloud app and configure this with your nextcloud credentials
- activate developer options in settings
- configure Seedvault. When asked to confirm the 12 word passphrase make sure to fill in the 12 words you used with your backup
- Enable USB debugging
- Connect your phone with a USB cable to your pc/laptop. Allow your pc/laptop on your phone.
- start the restore with: adb shell am start-activity -a com.stevesoltys.seedvault.RESTORE_BACKUP

This works, but it could have a more user friendly approach.

**Comment by grote** [comment]
This is **not** a Seedvault issue. The OEM (or integrator, LineageOS in your case) needs to ensure that apps that it allows for backup (see [`config.xml`](https://github.com/seedvault-app/seedvault/blob/d53f0fcde2202b79f83d7b77817e1face6c98e13/app/src/main/res/values/config.xml)), are available when restoring. Also, they can decide to make restore available outside of SetupWizard as well. This is all configurable in Seedvault since first release.

How can it be Seedvault's responsibility to enure that certain apps are available during SetupWizard?

**Comment by rugk** [comment]
Well… is there a way to manually trigger the backup restoration outside of the setup wizard?
