### ISSUE TITLE
Google Play Services no backup notification dismiss

### ISSUE THREAD

**Issue by ElucGeek** [seedvault-app/seedvault#280]
I have set a backup to a local folder that is then uploaded to an external device with Syncthing (as I cannot make Nextcloud backup work, see my other issue). It looks to work fine but after some hours Google Play Services send a notification: "Device isn't backed up". When I click it open the setup for Google Backup, if I close it, it comes back, if I click that I don't want to backup [with Google Backup] it automatically disable the backup from SeedVault. If I enable again, the notification comes back eventually.
For now I've just disabled the backup notification from Google Play Services but there might be a better way to address this and away new user to disable their SeedVault by mistake or getting crazy by the notification coming back every hour.

**Comment by grote** [comment]
This doesn't really sound like a Seedvault issue, but a Play Services one. I am not using Play Services myself, so somebody else would need to see if there's a way to trick play services into thinking that things get backed up.

They probably only check if their own backup transport is enabled instead of checking if *any* backup transport is enabled.

**Comment by ElucGeek** [comment]
Yes, but Google will not address this. Maybe it's at the ROM side that something can be done. At least my ticket might help if other have the same issue, so they can disable the backup notification from Google Play Services.

**Comment by grote** [comment]
Sorry, but we try not to keep too many open tickets around.
