### ISSUE TITLE
Implement a generic WebDAV backend

### ISSUE THREAD

**Issue by MajorP93** [seedvault-app/seedvault#317]
* [x] Refactor Seedvault’s storage and UI code to allow for different (non-SAF) storage plugins
  * [x]  don't allow changing storage while file or app backup is running
* [x] Implement new WebDAV storage plugin
* [x] UI for adding WebDAV credentials and URL

---

Hey,

first of all thanks for providing a FOSS backup solution for Android! Much appreciated!

As already mentioned in #84 I would like to request a generic WebDAV backend as storage provider.

I think this would come in handy to many users since it enables to use any cloud solution as backup target as long it supports WebDAV (many FOSS cloud solutions like Seafile, OwnCloud, NextCloud, Syncthing support WebDAV).

When selecting the WebDAV backend as storage provider a small configuration panel should open in which server, port, https (yes/no), path on the server, username and password can be entered. 

Thanks!

**Comment by Migsi** [comment]
This idea is great, as it would overcome the neccessity to have installed nextcloud on a freshly setup device, before being able to restore from it! (See #251 for reference)

**Comment by Forage** [comment]
Forgive my ignorance, but if I'm not mistaken you can install DAVx5, configure a WebDAV connection in that app, followed by selecting the app as a Seedvault backup provider.

**Comment by Zocker1999NET** [comment]
> Forgive my ignorance, but if I'm not mistaken you can install DAVx5, configure a WebDAV connection in that app, followed by selecting the app as a Seedvault backup provider.

In theory, this should work. I still hope that a native backend may come because using Android’s Storage Access Framework has some disvantages:
- as already mentioned by others, when setting up a new phone, you cannot immediately restore all apps’ configurations but need first to install & configure DAVx5 and then restore the backup.
- Backuping via either the Nextcloud app or DAVx5 to the same Nextcloud instance failed on my device after several tries with different configurations. Bug hunting this is increasingly difficult because the error could be caused by LineageOS (Storage Access Framework), DAVx5, Seedvault, or a combination of those.
    - Integrating WebDAV makes debugging easier as mainly Seedvault is to be checked.
-  When it worked on my device, Seedvault could not check if the upload was finished. Hence, it declared the backup finished, while Nextcloud was still busy uploading things. Nextcloud even sometimes failed to upload some stuff, and then waited for the user to retry it. So without manual intervention, it could leave you with a inconsistent backup.
    - Integrating WebDAV allows Seedvault to control that so its easier to ensure everything is uploaded & that in all cases, the backup copy online is usable.

If DAVx5 via SAF works for you or others, that’s great. I did use Seedvault via Nextcloud app until it suddenly broke after an update. But IMO such setup was never stable enough to configure it on devices of non tech-savy users. I hope that the integrated WebDAV becomes a fire-and-forget & just-works solution.
